/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedConfigRouteImport } from './routes/_authenticated/config'
import { Route as AuthenticatedEstoqueRouteImport } from './routes/_authenticated/estoque'
import { Route as AuthenticatedRevendaRouteImport } from './routes/_authenticated/revenda'
import { Route as AuthenticatedPeriodoIdRouteImport } from './routes/_authenticated/periodo.$id'

const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/_authenticated/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConfigRoute = AuthenticatedConfigRouteImport.update({
  id: '/_authenticated/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEstoqueRoute = AuthenticatedEstoqueRouteImport.update({
  id: '/_authenticated/estoque',
  path: '/estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRevendaRoute = AuthenticatedRevendaRouteImport.update({
  id: '/_authenticated/revenda',
  path: '/revenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPeriodoIdRoute = AuthenticatedPeriodoIdRouteImport.update({
  id: '/_authenticated/periodo/$id',
  path: '/periodo/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/config': typeof AuthenticatedConfigRoute
  '/estoque': typeof AuthenticatedEstoqueRoute
  '/revenda': typeof AuthenticatedRevendaRoute
  '/': typeof AuthenticatedIndexRoute
  '/periodo/$id': typeof AuthenticatedPeriodoIdRoute
}
export interface FileRoutesByTo {
  '/config': typeof AuthenticatedConfigRoute
  '/estoque': typeof AuthenticatedEstoqueRoute
  '/revenda': typeof AuthenticatedRevendaRoute
  '/': typeof AuthenticatedIndexRoute
  '/periodo/$id': typeof AuthenticatedPeriodoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/config': typeof AuthenticatedConfigRoute
  '/_authenticated/estoque': typeof AuthenticatedEstoqueRoute
  '/_authenticated/revenda': typeof AuthenticatedRevendaRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/periodo/$id': typeof AuthenticatedPeriodoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/config' | '/estoque' | '/revenda' | '/' | '/periodo/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/config' | '/estoque' | '/revenda' | '/' | '/periodo/$id'
  id:
    | '__root__'
    | '/_authenticated/config'
    | '/_authenticated/estoque'
    | '/_authenticated/revenda'
    | '/_authenticated/'
    | '/_authenticated/periodo/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedConfigRoute: typeof AuthenticatedConfigRoute
  AuthenticatedEstoqueRoute: typeof AuthenticatedEstoqueRoute
  AuthenticatedRevendaRoute: typeof AuthenticatedRevendaRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedPeriodoIdRoute: typeof AuthenticatedPeriodoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/config': {
      id: '/_authenticated/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof AuthenticatedConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/estoque': {
      id: '/_authenticated/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof AuthenticatedEstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/revenda': {
      id: '/_authenticated/revenda'
      path: '/revenda'
      fullPath: '/revenda'
      preLoaderRoute: typeof AuthenticatedRevendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/periodo/$id': {
      id: '/_authenticated/periodo/$id'
      path: '/periodo/$id'
      fullPath: '/periodo/$id'
      preLoaderRoute: typeof AuthenticatedPeriodoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedConfigRoute: AuthenticatedConfigRoute,
  AuthenticatedEstoqueRoute: AuthenticatedEstoqueRoute,
  AuthenticatedRevendaRoute: AuthenticatedRevendaRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedPeriodoIdRoute: AuthenticatedPeriodoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
